/*

 WALLMAP1TILE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\c_code\projects\wall_collisions\walls.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WallMap1tileWidth 20
#define WallMap1tileHeight 18
#define WallMap1tileBank 0

extern unsigned char WallMap1tile[];

/* End of WALLMAP1TILE.H */
