/*

 WALL_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 12
   Tile set      : C:\c_code\projects\wall_collisions\walls.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WallMapWidth 9
#define WallMapHeight 12
#define WallMapBank 0

extern unsigned char WallMap[];

/* End of WALL_MAP.H */
