/*

 WALLMAP4TILE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : wallSprites4tile.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WallMap4tileWidth 20
#define WallMap4tileHeight 18
#define WallMap4tileBank 0

extern unsigned char WallMap4tile[];

/* End of WALLMAP4TILE.H */
