/*
    BKG_MAP.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_BKG_MAP_H__
#define __MAP_BKG_MAP_H__

#define BKG_MAP_WIDTH 20
#define BKG_MAP_HEIGHT 18

extern const void __bank_BKG_MAP_DATA;

extern const unsigned char BKG_MAP_DATA[];

#endif
