/*
    BKG_TILES.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_BKG_TILES_H__
#define __MAP_BKG_TILES_H__

#define BKG_TILE_COUNT 5

#define BKG_PALETTE 0x1B

extern const void __bank_BKG_TILE_DATA;

extern const unsigned char BKG_TILE_DATA[];

#endif
