/*
    COLLISIONS_MAP.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_COLLISIONS_MAP_H__
#define __MAP_COLLISIONS_MAP_H__

#define COLLISIONS_MAP_WIDTH 20
#define COLLISIONS_MAP_HEIGHT 18

extern const void __bank_COLLISIONS_MAP_DATA;

extern const unsigned char COLLISIONS_MAP_DATA[];

#endif
