/*
    COLLISIONS_AESPRITE_MAP.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_COLLISIONS_AESPRITE_MAP_H__
#define __MAP_COLLISIONS_AESPRITE_MAP_H__

#define COLLISIONS_AESPRITE_MAP_WIDTH 20
#define COLLISIONS_AESPRITE_MAP_HEIGHT 18

extern const void __bank_COLLISIONS_AESPRITE_MAP_DATA;

extern const unsigned char COLLISIONS_AESPRITE_MAP_DATA[];

#endif
