/*
    MAP_MAP.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_MAP_MAP_H__
#define __MAP_MAP_MAP_H__

#define MAP_MAP_WIDTH 20
#define MAP_MAP_HEIGHT 18

extern const void __bank_MAP_MAP_DATA;

extern const unsigned char MAP_MAP_DATA[];

#endif
