/*
    MAP_TILES.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_MAP_TILES_H__
#define __MAP_MAP_TILES_H__

#define MAP_TILE_COUNT 5

#define MAP_PALETTE 0x1B

extern const void __bank_MAP_TILE_DATA;

extern const unsigned char MAP_TILE_DATA[];

#endif
