/*
    WALL_MAP.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_WALL_MAP_H__
#define __MAP_WALL_MAP_H__

#define WALL_MAP_WIDTH 20
#define WALL_MAP_HEIGHT 18

extern const void __bank_WALL_MAP_DATA;

extern const unsigned char WALL_MAP_DATA[];

#endif
