/*
    WALL_TILES.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_WALL_TILES_H__
#define __MAP_WALL_TILES_H__

#define WALL_TILE_COUNT 24

#define WALL_PALETTE 0x1B

extern const void __bank_WALL_TILE_DATA;

extern const unsigned char WALL_TILE_DATA[];

#endif
